# cloudbuild.yaml (for Google Cloud Build → Cloud Run deploy)
substitutions:
  _SERVICE_NAME: website-analyzer-backend
  _REGION: asia-southeast1

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID',
        '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest',
        '.'
      ]
  
  # Push the Docker image to Artifact/Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest']

  # Deploy to Cloud Run (managed). You can comment this step if you prefer manual deploy.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', '${_SERVICE_NAME}',
        '--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID',
        '--region', '${_REGION}',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '8000',
        '--memory', '2Gi',
        '--cpu', '2',
        '--max-instances', '10'
      ]

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '12000s'